name: Deploy Scaffolding Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      intent:
        type: choice
        description: "Intent of running Terraform workflow"
        default: plan
        options:
          - plan
          - apply
          - destroy
      environment:
        type: choice
        description: "Environment to deploy resource"
        default: development
        options:
          - development
          - production

permissions:
  id-token: write
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Create Deployment Matrix
    outputs:
      matrix: ${{ steps.get-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: get-matrix
        with:
          script: |
            const matrix = {
              "environment": context.payload?.inputs?.environment ? [context.payload.inputs.environment] : ["development", "production"],
              "intent": [context.payload?.inputs?.intent ?? "plan"]
            }
            console.log(matrix)
            return matrix
  build:
    needs: matrix
    runs-on: ubuntu-latest
    name: Run Matrix Build
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.environment }} ${{ matrix.intent }}
      - uses: actions/github-script@v7
        with:
          script: |
            console.log("${{ matrix.environment }}" === "development" ? "state" : "production")
